services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "template-postgres:/var/lib/postgresql/data"
    networks:
      - template-network

networks:
  template-network:
    driver: bridge

volumes:
  template-postgres:
    driver: local